### ISSUE TITLE
Tagy fungují pouze částečně (senkyr, main)

### ISSUE THREAD

**Issue by PlihalM** [sps-trutnov/projekt-galerie#37]
Pokud vyberu ITM a EPS, potvrdím filtry, tak se mi zobrazí všechny projekty ITM a EPS. (To je správně) Pokud ale odškrtnu ITM (nechám EPS zaškrtnuté), tak se  zobrazí všechny projekty.

**Comment by senkyr** [comment]
Totéž se děje ve větvi main.
