### ISSUE TITLE
Dlouhý popis (senkyr, main)

### ISSUE THREAD

**Issue by SprincJ** [sps-trutnov/projekt-galerie#39]
Pokud je popis moc dlouhý, nevejde se do svého divu na přehledové stránce. (refaktorizace)

**Comment by senkyr** [comment]
Platí i pro větev main.

**Comment by SprincJ** [comment]
Pull Request #55

**Comment by petruj** [comment]
V Pull Request #58 (do větve senkyr) pro popis a autory přidán scrollbar, text ve všech kolonkách nepřetéká, odřádkuje se.
