### ISSUE TITLE
Do vložení souborů v Upload lze vložit mp4 video (senkyr, main)

### ISSUE THREAD

**Issue by pchalek** [sps-trutnov/projekt-galerie#40]

**Comment by senkyr** [comment]
Přesněji řečeno - video soubor lze vybrat k uploadu, ale neuploaduje se a stránka s přehledem projektů následně spadne, protože nemá obrázek k zobrazení.

Totéž se děje ve větvi main.

**Comment by SprincJ** [comment]
#59
