### ISSUE TITLE
při spamu dlouhého textu ve všech kolonkách se nevejde do určitého místa (verze 1.1.1)

### ISSUE THREAD

**Issue by David-Binar** [sps-trutnov/projekt-galerie#42]
Chce to limit textu a nastavit to tak, kde mají být číslice tak budou číslice a kde bude pouze text bude písmenka

**Comment by petruj** [comment]
U detailu v popise opraveno.

**Comment by David-Binar** [comment]
opraveno

**Comment by senkyr** [comment]
Rád bych ty opravy viděl v nějakém commitu, ideálně pull-requestovaném. Dá se tu na něj i odkazovat přes #
