### ISSUE TITLE
Zobrazit více na hlavní stránce může zmizet, pokud bude mnoho textu v buňce (main, senkyr)

### ISSUE THREAD

**Issue by David-Binar** [sps-trutnov/projekt-galerie#45]
Návrh: místo zobrazit více by bylo dobré, aby se dalo kliknout kdekoliv v buňce pro rozkliknutí článku

**Comment by senkyr** [comment]
Myslím, že nejlepší by bylo moci klikat přímo na titulek projektu pro zobrazení jeho detailů. To je vždycky můj první pokus - až pak si uvědomím, že musím klikat na _Zobrazit více_.

**Comment by alesknizek** [comment]
upravil jsem kód v main.ejs tak aby se krátký popis omezil na 350 znaků, a je to v commitu #53

**Comment by David-Binar** [comment]
Odkaz na detail projektu dán na titulek projektu
- zobrazení více vymazáno
pull request #56
