### ISSUE TITLE
Při vytváření článku lze do textu vložit skript (senkyr, main)

### ISSUE THREAD

**Issue by SprincJ** [sps-trutnov/projekt-galerie#46]
Většina věcí, co se dá mezi `<script></script>` funguje, ale **nemá**.

**Comment by senkyr** [comment]
Konkrétně při vložení skriptu do popisu projektu se tento ve větvi senkyr vykoná při odhlášení admina. Jde tedy o problém při načítání projektů pro stránku s přehledem.

Ve větvi main se skript nespustí, ale do stránky s přehledem projektů prosákne kus JS zdrojáku z HTML souboru (řádky 21 až 23). Tohle prosáknutí se děje i ve větvi senkyr, půjde tedy o související problém.

**Comment by senkyr** [comment]
Mohlo by pomoct: [DOMParser](https://stackoverflow.com/questions/1912501/unescape-html-entities-in-javascript)

**Comment by senkyr** [comment]
Zkusím se na to ještě podívat. Ve větvi `senkyr-test` je zatím zbavení se speciálních znaků na straně serveru při ukládání projektů do databáze.

**Comment by senkyr** [comment]
Ve větvi `senkyr` jsem to opravil tím, že se ze všech textových vstupů před uložením odstraní znaky `<` a `>`
