### ISSUE TITLE
Přetýká název projektu v přehledu (senkyr)

### ISSUE THREAD

**Issue by synekm** [sps-trutnov/projekt-galerie#78]

**Comment by senkyr** [comment]
Už zase? Já myslel, že toto se už opravovalo.

**Comment by synekm** [comment]
V commitu 64c9ec623cbd5e847cb5e80e2d09b2145bce9d4d stále jde dát strašně dlouhý název projektu a tím ho přetéct na přehledu.

**Comment by synekm** [comment]
Melo by byt opraveno v pull requestu #81
