### ISSUE TITLE
Při uploadu projektu v admin režimu je slovo ADMIN moc nalevo (senkyr)

### ISSUE THREAD

**Issue by senkyr** [sps-trutnov/projekt-galerie#79]
Lépe by to vypadalo, kdyby odkaz ADMIN měl zleva stejné odsazení, jako má odkaz ZPĚT odsazení zprava.

**Comment by synekm** [comment]
Mělo by být upraveno v pull requestu #80

**Comment by synekm** [comment]
Melo by byt opraveno v pull requestu #81
